const test=require('node:test');
const assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const fs=require('node:fs');
const path=require('node:path');

test('device upload and library selection stay in the editor and require a verified save', async()=>{
  const dom=new JSDOM('<div id="journal-desk"></div><div id="announcements"></div><script id="desk-config" type="application/json"></script>',{url:'https://example.com/journal-desk/',runScripts:'outside-only'});
  const w=dom.window; const d=w.document; const calls=[];
  d.querySelector('#desk-config').textContent=JSON.stringify({apiBase:'https://example.com/wp-json/lunara/v1/',nonce:'nonce',deskUrl:'https://example.com/journal-desk/',siteUrl:'https://example.com/',name:'Dalton',maxUploadBytes:10485760});
  w.scrollTo=()=>{}; w.confirm=()=>true;
  const workspace={revision:'rev1',validation:{valid:true},workspace:{id:42,title:'Draft',content:'<p>Original</p>',excerpt:'Summary',featured_media:9,image:{url:'https://example.com/old.jpg'},acf:{journal_image_credit:'Old credit',journal_image_alt:'Old alt'},publication:{gpt_publish_enabled:true}}};
  const media=[{id:15,url:'https://example.com/new.jpg',thumbnail:'https://example.com/thumb.jpg',alt:'A new still',title:'New still',width:1600,height:900}];
  w.fetch=async(url,opts)=>{
    calls.push({url,opts});let data;
    if(url.includes('/save'))return {ok:false,headers:{get:()=> 'application/json'},json:async()=>({message:'Reload after partial save',data:{partial_save:true}})};
    if(url.includes('/media'))data={images:media,total_pages:2};
    else if(url.endsWith('/drafts/42'))data=workspace;
    else if(url.endsWith('/settings'))data={publication:{can_publish:true},voice:{banned_phrases:[]}};
    else data={drafts:[{id:42,title:'Draft'}],draft_count:1,dispatch:{},pagination:{}};
    return {ok:true,headers:{get:()=> 'application/json'},json:async()=>data};
  };
  const flush=async()=>{for(let i=0;i<12;i++)await new Promise(resolve=>setImmediate(resolve));};
  const click=async(selector)=>{const el=d.querySelector(selector);assert.ok(el,selector);el.click();await flush();};
  for(const file of ['desk-state.js','desk.js'])w.eval(fs.readFileSync(path.join(__dirname,'../assets/desk',file),'utf8'));
  await flush();await click('[data-draft="42"]');
  const editor=d.querySelector('#article-editor');editor.innerHTML='<p>My unsaved writing</p>';editor.dispatchEvent(new w.Event('input',{bubbles:true}));
  await click('[data-action="change-image"]');
  const upload=d.querySelector('#image-upload');Object.defineProperty(upload,'files',{value:[new w.File(['image bytes'],'still.jpg',{type:'image/jpeg'})]});upload.dispatchEvent(new w.Event('change',{bubbles:true}));await flush();
  const request=calls.find(call=>call.url.endsWith('/media')&&call.opts.method==='POST');
  assert.ok(request.opts.body instanceof w.FormData);
  assert.equal(request.opts.headers['Content-Type'],undefined);
  assert.equal(request.opts.headers['X-WP-Nonce'],'nonce');
  assert.equal(d.querySelector('#article-editor').textContent,'My unsaved writing');
  assert.equal(d.querySelector('.article-image').src,'https://example.com/new.jpg');
  assert.equal(d.querySelector('#image-credit').value,'');
  assert.equal(d.querySelector('#image-alt').value,'A new still');
  assert.equal(d.querySelector('#publish-button').disabled,true);
  await click('[data-action="change-image"]');await click('[data-action="media-library"]');
  d.querySelector('#media-search').value='film & still';d.querySelector('#media-search-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();
  assert.ok(calls.some(call=>call.url.includes('search=film%20%26%20still')));
  await click('[data-media-page="2"]');assert.ok(calls.some(call=>call.url.includes('page=2')));
  await click('[data-image="15"]');
  const credit=d.querySelector('#image-credit');credit.value='Studio / Photographer';credit.dispatchEvent(new w.Event('input',{bubbles:true}));
  await click('#save-button');
  const saved=JSON.parse(calls.find(call=>call.url.endsWith('/save')).opts.body);
  assert.equal(saved.featured_media,15);assert.equal(saved.content,'<p>My unsaved writing</p>');assert.equal(saved.acf.journal_image_credit,'Studio / Photographer');
  assert.equal(d.querySelector('#save-button').disabled,true,'An unverified partial save must require reload');
  assert.equal(d.querySelector('#publish-button').disabled,true);
  assert.equal(d.querySelector('#article-editor').textContent,'My unsaved writing');
  assert.equal(calls.some(call=>call.url.includes('/publish')),false);
  dom.window.close();
});
